<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Person.proto

namespace Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.PersonInfoResp</code>
 */
class PersonInfoResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Error = 1;</code>
     */
    protected $Error = 0;
    /**
     * Generated from protobuf field <code>string Msg = 2;</code>
     */
    protected $Msg = '';
    /**
     * Generated from protobuf field <code>.services.PersonRespData data = 3;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Error
     *     @type string $Msg
     *     @type \Services\PersonRespData $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Person::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 Error = 1;</code>
     * @return int
     */
    public function getError()
    {
        return $this->Error;
    }

    /**
     * Generated from protobuf field <code>int32 Error = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkInt32($var);
        $this->Error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->Msg;
    }

    /**
     * Generated from protobuf field <code>string Msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->Msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.services.PersonRespData data = 3;</code>
     * @return \Services\PersonRespData|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>.services.PersonRespData data = 3;</code>
     * @param \Services\PersonRespData $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Services\PersonRespData::class);
        $this->data = $var;

        return $this;
    }

}

